### ISSUE TITLE
directory-bootstrap doesn't work for Arch

### ISSUE THREAD

**Issue by rgeorgiev583** [hartwork/image-bootstrap#80]
```
# directory-bootstrap arch /mnt
Checking for chroot... /usr/sbin/chroot
Checking for gpg... /usr/sbin/gpg
Checking for mount... /usr/sbin/mount
Checking for umount... /usr/sbin/umount
Checking for wget... /usr/sbin/wget

Unsharing Linux namespaces (mount, UTS/hostname)...
Creating directory "/var/cache/directory-bootstrap"...
Checking access to "/mnt"...
Downloading image listing...
Downloading keyring listing...
Downloading "https://sources.archlinux.org/other/archlinux-keyring/archlinux-keyring-20190827.tar.gz.sig"...
Downloading "https://sources.archlinux.org/other/archlinux-keyring/archlinux-keyring-20190827.tar.gz"...
Initializing temporary GnuPG home at "/tmp/tmpXyNdyr/gpg_home"...
Downloading "https://raw.githubusercontent.com/gpg/gnupg/master/dirmngr/sks-keyservers.netCA.pem"...
Importing GPG keys whitelisted to sign archlinux-keyring...
Keys found allowed to sign archlinux-keyring tarball:
  - Bartlomiej Piotrowski <bpiotrowski@archlinux.org> (F3691687D867B81B51CE07D9BBE43771487328A9)
  - Christian Hesse <Christi@n-Hes.se> (BD84DE71F493DF6814B0167254EDC91609BC9183)
  - Evangelos Foutras <evangelos@foutrelis.com> (86CFFCA918CF3AF47147588051E8B148A9999C34)
  - Florian Pritz <bluewind@xinu.at> (CFA6AF15E5C74149FC1D8C086D1655C14CE1C13E)
  - Jelle van der Waa <jelle@archlinux.org> (E499C79F53C96A54E572FEE1C06086337C50773E)
  - Pierre Schmitz <pierre@archlinux.de> (4AA4767BBC9C4B1D18AE28B77F2D434B9741E8AC)
  - Thomas Bächler <thomas@bchlr.de> (A314827C4E4250A204CE6E13284FC34C8E4B1A25)
Importing GPG keys from the internet...
Importing GPG keys from disk...
Importing GPG key from file "/usr/lib/python2.7/site-packages/directory_bootstrap/resources/arch/86CFFCA918CF3AF47147588051E8B148A9999C34.asc"...
Importing GPG key from file "/usr/lib/python2.7/site-packages/directory_bootstrap/resources/arch/F3691687D867B81B51CE07D9BBE43771487328A9.asc"...
Importing GPG key from file "/usr/lib/python2.7/site-packages/directory_bootstrap/resources/arch/A314827C4E4250A204CE6E13284FC34C8E4B1A25.asc"...
Importing GPG key from file "/usr/lib/python2.7/site-packages/directory_bootstrap/resources/arch/BD84DE71F493DF6814B0167254EDC91609BC9183.asc"...
Importing GPG key from file "/usr/lib/python2.7/site-packages/directory_bootstrap/resources/arch/CFA6AF15E5C74149FC1D8C086D1655C14CE1C13E.asc"...
Importing GPG key from file "/usr/lib/python2.7/site-packages/directory_bootstrap/resources/arch/4AA4767BBC9C4B1D18AE28B77F2D434B9741E8AC.asc"...
Importing GPG key from file "/usr/lib/python2.7/site-packages/directory_bootstrap/resources/arch/E499C79F53C96A54E572FEE1C06086337C50773E.asc"...
Verifying integrity of file "/var/cache/directory-bootstrap/archlinux-keyring-20190827.tar.gz"...
Importing GPG key from file "/tmp/tmpXyNdyr/archlinux-keyring-20190827/archlinux.gpg"...
Downloading "https://mirrors.kernel.org/archlinux/iso/2019.09.01/archlinux-bootstrap-2019.09.01-x86_64.tar.gz.sig"...
Downloading "https://mirrors.kernel.org/archlinux/iso/2019.09.01/archlinux-bootstrap-2019.09.01-x86_64.tar.gz"...
Verifying integrity of file "/var/cache/directory-bootstrap/archlinux-bootstrap-2019.09.01-x86_64.tar.gz"...
Extracting bootstrap image to "/tmp/tmpXyNdyr/pacstrap_root/"...
Cleaning up "/tmp/tmpXyNdyr"...
Error: 'utf8' codec can't decode byte 0x80 in position 4: invalid start byte
If this looks like a bug to you, please file a report at https://github.com/hartwork/image-bootstrap.  Thank you!
```

I'm running the command on a Manjaro Linux host system (which is a distribution compatible with Arch).

**Comment by hartwork** [comment]
Do you happen to be using python 3?

**Comment by hartwork** [comment]
Nevermind, `#! /usr/bin/env python2` doesn't make that too likely :)

**Comment by rgeorgiev583** [comment]
@hartwork, as you already mentioned, the shebang for the `directory-bootstrap` command points to `python2`, which would override the default Python installation for my system (which is Python 3 indeed).

**Comment by hartwork** [comment]
Confirming for Git `master` a2f6f2b1a82a0ac4926e2fbcb5eab0199094d95f:

```console
# sudo ./directory-bootstrap --debug --verbose arch /tmp/arch_1                                            
[..]
Extracting bootstrap image to "/tmp/tmpEdj0JJ/pacstrap_root/"...
Cleaning up "/tmp/tmpEdj0JJ"...
Traceback (most recent call last):
  File "/home/sping/__playground/image-bootstrap/directory_bootstrap/shared/output_control.py", line 40, in run_handle_errors
    main_function(messenger, options)
  File "/home/sping/__playground/image-bootstrap/directory_bootstrap/__main__.py", line 43, in _main__level_three
    bootstrap.run()
  File "/home/sping/__playground/image-bootstrap/directory_bootstrap/distros/arch.py", line 286, in run
    abs_pacstrap_inner_root = self._extract_image(image_filename, abs_temp_dir)
  File "/home/sping/__playground/image-bootstrap/directory_bootstrap/distros/arch.py", line 113, in _extract_image
    tf.extractall(path=abs_pacstrap_outer_root)
  File "/usr/lib64/python2.7/tarfile.py", line 2075, in extractall
    for tarinfo in members:
  File "/usr/lib64/python2.7/tarfile.py", line 2510, in next
    tarinfo = self.tarfile.next()
  File "/usr/lib64/python2.7/tarfile.py", line 2358, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python2.7/tarfile.py", line 1254, in fromtarfile
    return obj._proc_member(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1276, in _proc_member
    return self._proc_pax(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1406, in _proc_pax
    value = value.decode("utf8")
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 4: invalid start byte
Error: 'utf8' codec can't decode byte 0x80 in position 4: invalid start byte
[..]
```

**Comment by hartwork** [comment]
Confirming for Git `master` a2f6f2b1a82a0ac4926e2fbcb5eab0199094d95f:

```console
# sudo ./directory-bootstrap --debug --verbose arch /tmp/arch_1                                            
[..]
Extracting bootstrap image to "/tmp/tmpEdj0JJ/pacstrap_root/"...
Cleaning up "/tmp/tmpEdj0JJ"...
Traceback (most recent call last):
  File "[..]/image-bootstrap/directory_bootstrap/shared/output_control.py", line 40, in run_handle_errors
    main_function(messenger, options)
  File "[..]/image-bootstrap/directory_bootstrap/__main__.py", line 43, in _main__level_three
    bootstrap.run()
  File "[..]/image-bootstrap/directory_bootstrap/distros/arch.py", line 286, in run
    abs_pacstrap_inner_root = self._extract_image(image_filename, abs_temp_dir)
  File "[..]/image-bootstrap/directory_bootstrap/distros/arch.py", line 113, in _extract_image
    tf.extractall(path=abs_pacstrap_outer_root)
  File "/usr/lib64/python2.7/tarfile.py", line 2075, in extractall
    for tarinfo in members:
  File "/usr/lib64/python2.7/tarfile.py", line 2510, in next
    tarinfo = self.tarfile.next()
  File "/usr/lib64/python2.7/tarfile.py", line 2358, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python2.7/tarfile.py", line 1254, in fromtarfile
    return obj._proc_member(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1276, in _proc_member
    return self._proc_pax(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1406, in _proc_pax
    value = value.decode("utf8")
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 4: invalid start byte
Error: 'utf8' codec can't decode byte 0x80 in position 4: invalid start byte
[..]
```

**Comment by hartwork** [comment]
I'm confused:

```
# cd "$(mktemp -d)"
# sudo tar xf /var/cache/directory-bootstrap/archlinux-bootstrap-2019.09.01-x86_64.tar.gz ; echo $?
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.capability'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.capability'
0

# sudo python2 -c $'from tarfile import TarFile\nwith TarFile.open("/var/cache/directory-bootstrap/archlinux-bootstrap-2019.09.01-x86_64.tar.gz") as tf:\n\ttf.extractall(path="'$(mktemp -d)'")'
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/lib64/python2.7/tarfile.py", line 2075, in extractall
    for tarinfo in members:
  File "/usr/lib64/python2.7/tarfile.py", line 2510, in next
    tarinfo = self.tarfile.next()
  File "/usr/lib64/python2.7/tarfile.py", line 2358, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib64/python2.7/tarfile.py", line 1254, in fromtarfile
    return obj._proc_member(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1276, in _proc_member
    return self._proc_pax(tarfile)
  File "/usr/lib64/python2.7/tarfile.py", line 1406, in _proc_pax
    value = value.decode("utf8")
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 4: invalid start byte
```

Are we (really?) dealing with python bug here?

**Comment by hartwork** [comment]
Using plain `tar(1)` on Git `master` now. Happy to re-open if the problem shows up again.
