### ISSUE TITLE
2.0.3 fails to run with Python 2.7 on Debian 10

### ISSUE THREAD

**Issue by frederictobiasc** [hartwork/image-bootstrap#86]
If I follow the instructions for building it on debian, I get the following error:

```
root# image-bootstrap --help
Traceback (most recent call last):
  File "/usr/bin/image-bootstrap", line 11, in <module>
    load_entry_point('image-bootstrap==2.0.3', 'console_scripts', 'image-bootstrap')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/image_bootstrap/__main__.py", line 8, in <module>
    from directory_bootstrap.distros.base import \
  File "/usr/lib/python2.7/dist-packages/directory_bootstrap/distros/base.py", line 45
    class DirectoryBootstrapper(object, metaclass=ABCMeta):
                                                 ^
SyntaxError: invalid syntax
```

**Comment by hartwork** [comment]
The backtrace shows that you're running image-bootstrap with Python 2.7 while 3.6 is required and available in Debian 10/buster. Please re-install image-bootstrap for Python 3.6. Does it work now?

**Comment by frederictobiasc** [comment]
Hi, thanks for your replay. I decided to change the VPS provider.
